# Generated by Django 3.1.6 on 2021-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_audiobook', models.CharField(max_length=100)),
                ('author_of_the_title', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.IntegerField()),
                ('uploaded_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_podcast', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.IntegerField()),
                ('uploaded_time', models.DateField()),
                ('host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_song', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.IntegerField()),
                ('uploaded_time', models.DateField()),
            ],
        ),
    ]
