# Generated by Django 3.1.6 on 2021-05-05 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210502_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_book',
            old_name='author_of_the_title',
            new_name='Author_of_the_Title',
        ),
        migrations.RenameField(
            model_name='audio_book',
            old_name='narrator',
            new_name='Narrator',
        ),
        migrations.RenameField(
            model_name='audio_book',
            old_name='title_of_the_audiobook',
            new_name='Title_of_the_Audiobook',
        ),
        migrations.RenameField(
            model_name='audio_book',
            old_name='uploaded_time',
            new_name='Uploaded_time',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='host',
            new_name='Host',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='uploaded_time',
            new_name='Uploaded_time',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='file_path',
            new_name='File_path',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='uploaded_time',
            new_name='Uploaded_time',
        ),
        migrations.AddField(
            model_name='audio_book',
            name='File_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='File_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='Participants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
