# Generated by Django 3.1.6 on 2021-05-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210505_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='Name_of_the_podcast',
            new_name='Name_of_the_Podcast',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Name_of_the_song',
            new_name='Name_of_the_Song',
        ),
    ]
